/* Generated by Cython 0.14 on Sun Nov 13 23:22:04 2011 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#ifndef Py_PYTHON_H
    #error Python headers needed to compile C extensions, please install development version of Python.
#else

#include <stddef.h> /* For offsetof */
#ifndef offsetof
#define offsetof(type, member) ( (size_t) & ((type*)0) -> member )
#endif

#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
  #ifndef __fastcall
    #define __fastcall
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(t) t
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif

#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif

#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
  #define PyDict_CheckExact(op) (Py_TYPE(op) == &PyDict_Type)
  #define PyDict_Contains(d,o)   PySequence_Contains(d,o)
#endif

#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PY_FORMAT_SIZE_T ""
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
  #define PyErr_WarnEx(category, message, stacklevel) PyErr_Warn(category, message)
#endif

#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
     void *buf;
     PyObject *obj;
     Py_ssize_t len;
     Py_ssize_t itemsize;
     int readonly;
     int ndim;
     char *format;
     Py_ssize_t *shape;
     Py_ssize_t *strides;
     Py_ssize_t *suboffsets;
     void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif

#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif

#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif

#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyStringObject               PyUnicodeObject
  #define PyString_Type                PyUnicode_Type
  #define PyString_Check               PyUnicode_Check
  #define PyString_CheckExact          PyUnicode_CheckExact
#endif

#if PY_VERSION_HEX < 0x02060000
  #define PyBytesObject                PyStringObject
  #define PyBytes_Type                 PyString_Type
  #define PyBytes_Check                PyString_Check
  #define PyBytes_CheckExact           PyString_CheckExact
  #define PyBytes_FromString           PyString_FromString
  #define PyBytes_FromStringAndSize    PyString_FromStringAndSize
  #define PyBytes_FromFormat           PyString_FromFormat
  #define PyBytes_DecodeEscape         PyString_DecodeEscape
  #define PyBytes_AsString             PyString_AsString
  #define PyBytes_AsStringAndSize      PyString_AsStringAndSize
  #define PyBytes_Size                 PyString_Size
  #define PyBytes_AS_STRING            PyString_AS_STRING
  #define PyBytes_GET_SIZE             PyString_GET_SIZE
  #define PyBytes_Repr                 PyString_Repr
  #define PyBytes_Concat               PyString_Concat
  #define PyBytes_ConcatAndDel         PyString_ConcatAndDel
  #define PySet_Check(obj)             PyObject_TypeCheck(obj, &PySet_Type)
  #define PyFrozenSet_Check(obj)       PyObject_TypeCheck(obj, &PyFrozenSet_Type)
#endif

#ifndef PySet_CheckExact
#  define PySet_CheckExact(obj)          (Py_TYPE(obj) == &PySet_Type)
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyIntObject                  PyLongObject
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyBoolObject PyLongObject
#endif


#if PY_MAJOR_VERSION >= 3
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceTrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceDivide(x,y)
#endif

#if (PY_MAJOR_VERSION < 3) || (PY_VERSION_HEX >= 0x03010300)
  #define __Pyx_PySequence_GetSlice(obj, a, b) PySequence_GetSlice(obj, a, b)
  #define __Pyx_PySequence_SetSlice(obj, a, b, value) PySequence_SetSlice(obj, a, b, value)
  #define __Pyx_PySequence_DelSlice(obj, a, b) PySequence_DelSlice(obj, a, b)
#else
  #define __Pyx_PySequence_GetSlice(obj, a, b) (unlikely(!(obj)) ? \
        (PyErr_SetString(PyExc_SystemError, "null argument to internal routine"), (PyObject*)0) : \
        (likely((obj)->ob_type->tp_as_mapping) ? (PySequence_GetSlice(obj, a, b)) : \
            (PyErr_Format(PyExc_TypeError, "'%.200s' object is unsliceable", (obj)->ob_type->tp_name), (PyObject*)0)))
  #define __Pyx_PySequence_SetSlice(obj, a, b, value) (unlikely(!(obj)) ? \
        (PyErr_SetString(PyExc_SystemError, "null argument to internal routine"), -1) : \
        (likely((obj)->ob_type->tp_as_mapping) ? (PySequence_SetSlice(obj, a, b, value)) : \
            (PyErr_Format(PyExc_TypeError, "'%.200s' object doesn't support slice assignment", (obj)->ob_type->tp_name), -1)))
  #define __Pyx_PySequence_DelSlice(obj, a, b) (unlikely(!(obj)) ? \
        (PyErr_SetString(PyExc_SystemError, "null argument to internal routine"), -1) : \
        (likely((obj)->ob_type->tp_as_mapping) ? (PySequence_DelSlice(obj, a, b)) : \
            (PyErr_Format(PyExc_TypeError, "'%.200s' object doesn't support slice deletion", (obj)->ob_type->tp_name), -1)))
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) ((self) ? PyMethod_New(func, self) : PyInstanceMethod_New(func))
#endif

#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),((char *)(n)))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),((char *)(n)),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),((char *)(n)))
#else
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),(n))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),(n),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),(n))
#endif

#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_NAMESTR(n) ((char *)(n))
  #define __Pyx_DOCSTR(n)  ((char *)(n))
#else
  #define __Pyx_NAMESTR(n) (n)
  #define __Pyx_DOCSTR(n)  (n)
#endif

#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif

#if defined(WIN32) || defined(MS_WINDOWS)
#define _USE_MATH_DEFINES
#endif
#include <math.h>
#define __PYX_HAVE_API__kivy__graphics__buffer
#include "math.h"
#include "stdlib.h"
#include "string.h"

#ifdef PYREX_WITHOUT_ASSERTIONS
#define CYTHON_WITHOUT_ASSERTIONS
#endif


/* inline attribute */
#ifndef CYTHON_INLINE
  #if defined(__GNUC__)
    #define CYTHON_INLINE __inline__
  #elif defined(_MSC_VER)
    #define CYTHON_INLINE __inline
  #elif defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
    #define CYTHON_INLINE inline
  #else
    #define CYTHON_INLINE
  #endif
#endif

/* unused attribute */
#ifndef CYTHON_UNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define CYTHON_UNUSED __attribute__ ((__unused__))
#   else
#     define CYTHON_UNUSED
#   endif
# elif defined(__ICC) || defined(__INTEL_COMPILER)
#   define CYTHON_UNUSED __attribute__ ((__unused__))
# else
#   define CYTHON_UNUSED
# endif
#endif

typedef struct {PyObject **p; char *s; const long n; const char* encoding; const char is_unicode; const char is_str; const char intern; } __Pyx_StringTabEntry; /*proto*/


/* Type Conversion Predeclarations */

#define __Pyx_PyBytes_FromUString(s) PyBytes_FromString((char*)s)
#define __Pyx_PyBytes_AsUString(s)   ((unsigned char*) PyBytes_AsString(s))

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static CYTHON_INLINE int __Pyx_PyObject_IsTrue(PyObject*);
static CYTHON_INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x);

static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
static CYTHON_INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t);
static CYTHON_INLINE size_t __Pyx_PyInt_AsSize_t(PyObject*);

#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))


#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 || (__GNUC__ == 2 && (__GNUC_MINOR__ > 95))
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static PyObject *__pyx_empty_bytes;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;


static const char *__pyx_f[] = {
  "buffer.pyx",
};

/* Type declarations */

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pxd":1
 * cdef class Buffer:             # <<<<<<<<<<<<<<
 *     cdef void *data
 *     cdef int *l_free
 */

struct __pyx_obj_4kivy_8graphics_6buffer_Buffer {
  PyObject_HEAD
  struct __pyx_vtabstruct_4kivy_8graphics_6buffer_Buffer *__pyx_vtab;
  void *data;
  int *l_free;
  int i_free;
  int block_size;
  int block_count;
};


/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":3
 * include "common.pxi"
 * 
 * cdef class Buffer:             # <<<<<<<<<<<<<<
 *     '''Buffer class is designed to manage very fast a list of fixed size block.
 *     You can easily add and remove data from the buffer.
 */

struct __pyx_vtabstruct_4kivy_8graphics_6buffer_Buffer {
  void (*clear)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *);
  void (*grow)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, int);
  void (*add)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, void *, unsigned short *, int);
  void (*remove)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, unsigned short *, int);
  int (*count)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *);
  int (*size)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *);
  void *(*pointer)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *);
  void *(*offset_pointer)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, int);
  void (*update)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, int, void *, int);
};
static struct __pyx_vtabstruct_4kivy_8graphics_6buffer_Buffer *__pyx_vtabptr_4kivy_8graphics_6buffer_Buffer;

#ifndef CYTHON_REFNANNY
  #define CYTHON_REFNANNY 0
#endif

#if CYTHON_REFNANNY
  typedef struct {
    void (*INCREF)(void*, PyObject*, int);
    void (*DECREF)(void*, PyObject*, int);
    void (*GOTREF)(void*, PyObject*, int);
    void (*GIVEREF)(void*, PyObject*, int);
    void* (*SetupContext)(const char*, int, const char*);
    void (*FinishContext)(void**);
  } __Pyx_RefNannyAPIStruct;
  static __Pyx_RefNannyAPIStruct *__Pyx_RefNanny = NULL;
  static __Pyx_RefNannyAPIStruct * __Pyx_RefNannyImportAPI(const char *modname) {
    PyObject *m = NULL, *p = NULL;
    void *r = NULL;
    m = PyImport_ImportModule((char *)modname);
    if (!m) goto end;
    p = PyObject_GetAttrString(m, (char *)"RefNannyAPI");
    if (!p) goto end;
    r = PyLong_AsVoidPtr(p);
  end:
    Py_XDECREF(p);
    Py_XDECREF(m);
    return (__Pyx_RefNannyAPIStruct *)r;
  }
  #define __Pyx_RefNannySetupContext(name)           void *__pyx_refnanny = __Pyx_RefNanny->SetupContext((name), __LINE__, __FILE__)
  #define __Pyx_RefNannyFinishContext()           __Pyx_RefNanny->FinishContext(&__pyx_refnanny)
  #define __Pyx_INCREF(r) __Pyx_RefNanny->INCREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_DECREF(r) __Pyx_RefNanny->DECREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GOTREF(r) __Pyx_RefNanny->GOTREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GIVEREF(r) __Pyx_RefNanny->GIVEREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_XDECREF(r) do { if((r) != NULL) {__Pyx_DECREF(r);} } while(0)
#else
  #define __Pyx_RefNannySetupContext(name)
  #define __Pyx_RefNannyFinishContext()
  #define __Pyx_INCREF(r) Py_INCREF(r)
  #define __Pyx_DECREF(r) Py_DECREF(r)
  #define __Pyx_GOTREF(r)
  #define __Pyx_GIVEREF(r)
  #define __Pyx_XDECREF(r) Py_XDECREF(r)
#endif /* CYTHON_REFNANNY */
#define __Pyx_XGIVEREF(r) do { if((r) != NULL) {__Pyx_GIVEREF(r);} } while(0)
#define __Pyx_XGOTREF(r) do { if((r) != NULL) {__Pyx_GOTREF(r);} } while(0)

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static CYTHON_INLINE int __Pyx_CheckKeywordStrings(PyObject *kwdict,
    const char* function_name, int kw_allowed); /*proto*/

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static CYTHON_INLINE long __Pyx_mod_long(long, long); /* proto */

static CYTHON_INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static CYTHON_INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static CYTHON_INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject *);

static CYTHON_INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject *);

static CYTHON_INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject *);

static CYTHON_INLINE char __Pyx_PyInt_AsChar(PyObject *);

static CYTHON_INLINE short __Pyx_PyInt_AsShort(PyObject *);

static CYTHON_INLINE int __Pyx_PyInt_AsInt(PyObject *);

static CYTHON_INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject *);

static CYTHON_INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject *);

static CYTHON_INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject *);

static CYTHON_INLINE int __Pyx_PyInt_AsLongDouble(PyObject *);

static CYTHON_INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject *);

static CYTHON_INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject *);

static CYTHON_INLINE long __Pyx_PyInt_AsLong(PyObject *);

static CYTHON_INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject *);

static CYTHON_INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject *);

static CYTHON_INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject *);

static void __Pyx_WriteUnraisable(const char *name); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
/* Module declarations from kivy.graphics.buffer */

static PyTypeObject *__pyx_ptype_4kivy_8graphics_6buffer_Buffer = 0;
static double __pyx_v_4kivy_8graphics_6buffer_pi;
#define __Pyx_MODULE_NAME "kivy.graphics.buffer"
int __pyx_module_is_main_kivy__graphics__buffer = 0;

/* Implementation of kivy.graphics.buffer */
static PyObject *__pyx_builtin_SystemError;
static PyObject *__pyx_builtin_xrange;
static char __pyx_k_1[] = "Unable to realloc memory for buffer";
static char __pyx_k_3[] = "Unable to realloc memory for free list";
static char __pyx_k__data[] = "data";
static char __pyx_k__grow[] = "grow";
static char __pyx_k__range[] = "range";
static char __pyx_k__i_free[] = "i_free";
static char __pyx_k__l_free[] = "l_free";
static char __pyx_k__xrange[] = "xrange";
static char __pyx_k____main__[] = "__main__";
static char __pyx_k____test__[] = "__test__";
static char __pyx_k__block_size[] = "block_size";
static char __pyx_k__SystemError[] = "SystemError";
static char __pyx_k__block_count[] = "block_count";
static PyObject *__pyx_kp_s_1;
static PyObject *__pyx_kp_s_3;
static PyObject *__pyx_n_s__SystemError;
static PyObject *__pyx_n_s____main__;
static PyObject *__pyx_n_s____test__;
static PyObject *__pyx_n_s__block_count;
static PyObject *__pyx_n_s__block_size;
static PyObject *__pyx_n_s__data;
static PyObject *__pyx_n_s__grow;
static PyObject *__pyx_n_s__i_free;
static PyObject *__pyx_n_s__l_free;
static PyObject *__pyx_n_s__range;
static PyObject *__pyx_n_s__xrange;
static PyObject *__pyx_k_tuple_2;
static PyObject *__pyx_k_tuple_4;

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":7
 *     You can easily add and remove data from the buffer.
 *     '''
 *     def __cinit__(self):             # <<<<<<<<<<<<<<
 *         self.data = NULL
 *         self.i_free = 0
 */

static int __pyx_pf_4kivy_8graphics_6buffer_6Buffer_0__cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_4kivy_8graphics_6buffer_6Buffer_0__cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  __Pyx_RefNannySetupContext("__cinit__");
  if (unlikely(PyTuple_GET_SIZE(__pyx_args) > 0)) {
    __Pyx_RaiseArgtupleInvalid("__cinit__", 1, 0, 0, PyTuple_GET_SIZE(__pyx_args)); return -1;}
  if (unlikely(__pyx_kwds) && unlikely(PyDict_Size(__pyx_kwds) > 0) && unlikely(!__Pyx_CheckKeywordStrings(__pyx_kwds, "__cinit__", 0))) return -1;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":8
 *     '''
 *     def __cinit__(self):
 *         self.data = NULL             # <<<<<<<<<<<<<<
 *         self.i_free = 0
 *         self.block_size = 0
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->data = NULL;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":9
 *     def __cinit__(self):
 *         self.data = NULL
 *         self.i_free = 0             # <<<<<<<<<<<<<<
 *         self.block_size = 0
 *         self.block_count = 0
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->i_free = 0;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":10
 *         self.data = NULL
 *         self.i_free = 0
 *         self.block_size = 0             # <<<<<<<<<<<<<<
 *         self.block_count = 0
 *         self.l_free = NULL
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->block_size = 0;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":11
 *         self.i_free = 0
 *         self.block_size = 0
 *         self.block_count = 0             # <<<<<<<<<<<<<<
 *         self.l_free = NULL
 * 
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->block_count = 0;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":12
 *         self.block_size = 0
 *         self.block_count = 0
 *         self.l_free = NULL             # <<<<<<<<<<<<<<
 * 
 *     def __dealloc__(self):
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->l_free = NULL;

  __pyx_r = 0;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":14
 *         self.l_free = NULL
 * 
 *     def __dealloc__(self):             # <<<<<<<<<<<<<<
 *         if self.data != NULL:
 *             free(self.data)
 */

static void __pyx_pf_4kivy_8graphics_6buffer_6Buffer_1__dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_pf_4kivy_8graphics_6buffer_6Buffer_1__dealloc__(PyObject *__pyx_v_self) {
  int __pyx_t_1;
  __Pyx_RefNannySetupContext("__dealloc__");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":15
 * 
 *     def __dealloc__(self):
 *         if self.data != NULL:             # <<<<<<<<<<<<<<
 *             free(self.data)
 *             self.data = NULL
 */
  __pyx_t_1 = (((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->data != NULL);
  if (__pyx_t_1) {

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":16
 *     def __dealloc__(self):
 *         if self.data != NULL:
 *             free(self.data)             # <<<<<<<<<<<<<<
 *             self.data = NULL
 *         self.block_count = 0
 */
    free(((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->data);

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":17
 *         if self.data != NULL:
 *             free(self.data)
 *             self.data = NULL             # <<<<<<<<<<<<<<
 *         self.block_count = 0
 *         self.block_size = 0
 */
    ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->data = NULL;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":18
 *             free(self.data)
 *             self.data = NULL
 *         self.block_count = 0             # <<<<<<<<<<<<<<
 *         self.block_size = 0
 *         if self.l_free != NULL:
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->block_count = 0;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":19
 *             self.data = NULL
 *         self.block_count = 0
 *         self.block_size = 0             # <<<<<<<<<<<<<<
 *         if self.l_free != NULL:
 *             free(self.l_free)
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->block_size = 0;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":20
 *         self.block_count = 0
 *         self.block_size = 0
 *         if self.l_free != NULL:             # <<<<<<<<<<<<<<
 *             free(self.l_free)
 * 
 */
  __pyx_t_1 = (((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->l_free != NULL);
  if (__pyx_t_1) {

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":21
 *         self.block_size = 0
 *         if self.l_free != NULL:
 *             free(self.l_free)             # <<<<<<<<<<<<<<
 * 
 *     def __init__(self, int block_size):
 */
    free(((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->l_free);
    goto __pyx_L6;
  }
  __pyx_L6:;

  __Pyx_RefNannyFinishContext();
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":23
 *             free(self.l_free)
 * 
 *     def __init__(self, int block_size):             # <<<<<<<<<<<<<<
 *         self.block_size = block_size
 * 
 */

static int __pyx_pf_4kivy_8graphics_6buffer_6Buffer_2__init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_4kivy_8graphics_6buffer_6Buffer_2__init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_block_size;
  int __pyx_r;
  static PyObject **__pyx_pyargnames[] = {&__pyx_n_s__block_size,0};
  __Pyx_RefNannySetupContext("__init__");
  if (unlikely(__pyx_kwds)) {
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    PyObject* values[1] = {0};
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__block_size);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "__init__") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_block_size = __Pyx_PyInt_AsInt(values[0]); if (unlikely((__pyx_v_block_size == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  } else if (PyTuple_GET_SIZE(__pyx_args) != 1) {
    goto __pyx_L5_argtuple_error;
  } else {
    __pyx_v_block_size = __Pyx_PyInt_AsInt(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((__pyx_v_block_size == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("__init__", 1, 1, 1, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("kivy.graphics.buffer.Buffer.__init__");
  __Pyx_RefNannyFinishContext();
  return -1;
  __pyx_L4_argument_unpacking_done:;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":24
 * 
 *     def __init__(self, int block_size):
 *         self.block_size = block_size             # <<<<<<<<<<<<<<
 * 
 *     cdef void grow(self, int block_count):
 */
  ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self)->block_size = __pyx_v_block_size;

  __pyx_r = 0;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":26
 *         self.block_size = block_size
 * 
 *     cdef void grow(self, int block_count):             # <<<<<<<<<<<<<<
 *         '''Automaticly realloc the memory if they are no enough block.
 *         Work only for "grow" operation, not the inverse.
 */

static  void __pyx_f_4kivy_8graphics_6buffer_6Buffer_grow(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self, int __pyx_v_block_count) {
  void *__pyx_v_newptr;
  int __pyx_v_i;
  long __pyx_v_diff;
  int __pyx_t_1;
  PyObject *__pyx_t_2 = NULL;
  int __pyx_t_3;
  int __pyx_t_4;
  __Pyx_RefNannySetupContext("grow");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":30
 *         Work only for "grow" operation, not the inverse.
 *         '''
 *         cdef void *newptr = NULL             # <<<<<<<<<<<<<<
 *         cdef int i
 *         cdef int l_free_tmp
 */
  __pyx_v_newptr = NULL;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":35
 * 
 *         # set block_count to the nearest 8 block
 *         diff = block_count % 8             # <<<<<<<<<<<<<<
 *         if diff != 0:
 *             block_count = (8 - (block_count % 8)) + block_count
 */
  __pyx_v_diff = __Pyx_mod_long(__pyx_v_block_count, 8);

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":36
 *         # set block_count to the nearest 8 block
 *         diff = block_count % 8
 *         if diff != 0:             # <<<<<<<<<<<<<<
 *             block_count = (8 - (block_count % 8)) + block_count
 * 
 */
  __pyx_t_1 = (__pyx_v_diff != 0);
  if (__pyx_t_1) {

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":37
 *         diff = block_count % 8
 *         if diff != 0:
 *             block_count = (8 - (block_count % 8)) + block_count             # <<<<<<<<<<<<<<
 * 
 *         if block_count < self.block_count:
 */
    __pyx_v_block_count = ((8 - __Pyx_mod_long(__pyx_v_block_count, 8)) + __pyx_v_block_count);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":39
 *             block_count = (8 - (block_count % 8)) + block_count
 * 
 *         if block_count < self.block_count:             # <<<<<<<<<<<<<<
 *             return
 * 
 */
  __pyx_t_1 = (__pyx_v_block_count < __pyx_v_self->block_count);
  if (__pyx_t_1) {

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":40
 * 
 *         if block_count < self.block_count:
 *             return             # <<<<<<<<<<<<<<
 * 
 *         # Try to realloc
 */
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":43
 * 
 *         # Try to realloc
 *         newptr = realloc(self.data, self.block_size * block_count)             # <<<<<<<<<<<<<<
 *         if newptr == NULL:
 *             raise SystemError('Unable to realloc memory for buffer')
 */
  __pyx_v_newptr = realloc(__pyx_v_self->data, (__pyx_v_self->block_size * __pyx_v_block_count));

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":44
 *         # Try to realloc
 *         newptr = realloc(self.data, self.block_size * block_count)
 *         if newptr == NULL:             # <<<<<<<<<<<<<<
 *             raise SystemError('Unable to realloc memory for buffer')
 * 
 */
  __pyx_t_1 = (__pyx_v_newptr == NULL);
  if (__pyx_t_1) {

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":45
 *         newptr = realloc(self.data, self.block_size * block_count)
 *         if newptr == NULL:
 *             raise SystemError('Unable to realloc memory for buffer')             # <<<<<<<<<<<<<<
 * 
 *         # Realloc work, put the new pointer
 */
    __pyx_t_2 = PyObject_Call(__pyx_builtin_SystemError, ((PyObject *)__pyx_k_tuple_2), NULL); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_2);
    __Pyx_Raise(__pyx_t_2, 0, 0);
    __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":48
 * 
 *         # Realloc work, put the new pointer
 *         self.data = newptr             # <<<<<<<<<<<<<<
 * 
 *         # Create the free blocks
 */
  __pyx_v_self->data = __pyx_v_newptr;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":51
 * 
 *         # Create the free blocks
 *         newptr = realloc(self.l_free, sizeof(int) * block_count)             # <<<<<<<<<<<<<<
 *         if newptr == NULL:
 *             raise SystemError('Unable to realloc memory for free list')
 */
  __pyx_v_newptr = realloc(__pyx_v_self->l_free, ((sizeof(int)) * __pyx_v_block_count));

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":52
 *         # Create the free blocks
 *         newptr = realloc(self.l_free, sizeof(int) * block_count)
 *         if newptr == NULL:             # <<<<<<<<<<<<<<
 *             raise SystemError('Unable to realloc memory for free list')
 *         self.l_free = <int *>newptr
 */
  __pyx_t_1 = (__pyx_v_newptr == NULL);
  if (__pyx_t_1) {

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":53
 *         newptr = realloc(self.l_free, sizeof(int) * block_count)
 *         if newptr == NULL:
 *             raise SystemError('Unable to realloc memory for free list')             # <<<<<<<<<<<<<<
 *         self.l_free = <int *>newptr
 * 
 */
    __pyx_t_2 = PyObject_Call(__pyx_builtin_SystemError, ((PyObject *)__pyx_k_tuple_4), NULL); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_2);
    __Pyx_Raise(__pyx_t_2, 0, 0);
    __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":54
 *         if newptr == NULL:
 *             raise SystemError('Unable to realloc memory for free list')
 *         self.l_free = <int *>newptr             # <<<<<<<<<<<<<<
 * 
 *         # Initialize the list with index of free block
 */
  __pyx_v_self->l_free = ((int *)__pyx_v_newptr);

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":57
 * 
 *         # Initialize the list with index of free block
 *         for i in xrange(self.block_count, block_count):             # <<<<<<<<<<<<<<
 *             self.l_free[i] = i
 * 
 */
  __pyx_t_3 = __pyx_v_block_count;
  for (__pyx_t_4 = __pyx_v_self->block_count; __pyx_t_4 < __pyx_t_3; __pyx_t_4+=1) {
    __pyx_v_i = __pyx_t_4;

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":58
 *         # Initialize the list with index of free block
 *         for i in xrange(self.block_count, block_count):
 *             self.l_free[i] = i             # <<<<<<<<<<<<<<
 * 
 *         # Update how many block are allocated
 */
    (__pyx_v_self->l_free[__pyx_v_i]) = __pyx_v_i;
  }

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":61
 * 
 *         # Update how many block are allocated
 *         self.block_count = block_count             # <<<<<<<<<<<<<<
 * 
 *     cdef void clear(self):
 */
  __pyx_v_self->block_count = __pyx_v_block_count;

  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_WriteUnraisable("kivy.graphics.buffer.Buffer.grow");
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":63
 *         self.block_count = block_count
 * 
 *     cdef void clear(self):             # <<<<<<<<<<<<<<
 *         '''Clear the whole buffer, and mark all blocks as available.
 *         '''
 */

static  void __pyx_f_4kivy_8graphics_6buffer_6Buffer_clear(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self) {
  int __pyx_v_i;
  int __pyx_t_1;
  int __pyx_t_2;
  __Pyx_RefNannySetupContext("clear");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":66
 *         '''Clear the whole buffer, and mark all blocks as available.
 *         '''
 *         for i in xrange(self.block_count):             # <<<<<<<<<<<<<<
 *             self.l_free[i] = i
 *         self.i_free = 0
 */
  __pyx_t_1 = __pyx_v_self->block_count;
  for (__pyx_t_2 = 0; __pyx_t_2 < __pyx_t_1; __pyx_t_2+=1) {
    __pyx_v_i = __pyx_t_2;

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":67
 *         '''
 *         for i in xrange(self.block_count):
 *             self.l_free[i] = i             # <<<<<<<<<<<<<<
 *         self.i_free = 0
 * 
 */
    (__pyx_v_self->l_free[__pyx_v_i]) = __pyx_v_i;
  }

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":68
 *         for i in xrange(self.block_count):
 *             self.l_free[i] = i
 *         self.i_free = 0             # <<<<<<<<<<<<<<
 * 
 *     cdef void add(self, void *blocks, unsigned short *indices, int count):
 */
  __pyx_v_self->i_free = 0;

  __Pyx_RefNannyFinishContext();
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":70
 *         self.i_free = 0
 * 
 *     cdef void add(self, void *blocks, unsigned short *indices, int count):             # <<<<<<<<<<<<<<
 *         '''Add a list of block inside our buffer
 *         '''
 */

static  void __pyx_f_4kivy_8graphics_6buffer_6Buffer_add(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self, void *__pyx_v_blocks, unsigned short *__pyx_v_indices, int __pyx_v_count) {
  int __pyx_v_i;
  int __pyx_v_block;
  void *__pyx_v_p;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  __Pyx_RefNannySetupContext("add");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":77
 * 
 *         # Ensure that our buffer is enough for having all the elements
 *         if count > self.block_count - self.i_free:             # <<<<<<<<<<<<<<
 *             self.grow(self.block_count + count)
 * 
 */
  __pyx_t_1 = (__pyx_v_count > (__pyx_v_self->block_count - __pyx_v_self->i_free));
  if (__pyx_t_1) {

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":78
 *         # Ensure that our buffer is enough for having all the elements
 *         if count > self.block_count - self.i_free:
 *             self.grow(self.block_count + count)             # <<<<<<<<<<<<<<
 * 
 *         # Add all the block inside our buffer
 */
    ((struct __pyx_vtabstruct_4kivy_8graphics_6buffer_Buffer *)__pyx_v_self->__pyx_vtab)->grow(__pyx_v_self, (__pyx_v_self->block_count + __pyx_v_count));
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":81
 * 
 *         # Add all the block inside our buffer
 *         for i in xrange(count):             # <<<<<<<<<<<<<<
 *             p = blocks + (self.block_size * i)
 * 
 */
  __pyx_t_2 = __pyx_v_count;
  for (__pyx_t_3 = 0; __pyx_t_3 < __pyx_t_2; __pyx_t_3+=1) {
    __pyx_v_i = __pyx_t_3;

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":82
 *         # Add all the block inside our buffer
 *         for i in xrange(count):
 *             p = blocks + (self.block_size * i)             # <<<<<<<<<<<<<<
 * 
 *             # Take a free block
 */
    __pyx_v_p = (__pyx_v_blocks + (__pyx_v_self->block_size * __pyx_v_i));

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":85
 * 
 *             # Take a free block
 *             block = self.l_free[self.i_free]             # <<<<<<<<<<<<<<
 *             self.i_free += 1
 * 
 */
    __pyx_v_block = (__pyx_v_self->l_free[__pyx_v_self->i_free]);

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":86
 *             # Take a free block
 *             block = self.l_free[self.i_free]
 *             self.i_free += 1             # <<<<<<<<<<<<<<
 * 
 *             # Copy content
 */
    __pyx_v_self->i_free = (__pyx_v_self->i_free + 1);

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":89
 * 
 *             # Copy content
 *             memcpy(self.data + (block * self.block_size), p, self.block_size)             # <<<<<<<<<<<<<<
 * 
 *             # Push the current block as indices
 */
    memcpy((__pyx_v_self->data + (__pyx_v_block * __pyx_v_self->block_size)), __pyx_v_p, __pyx_v_self->block_size);

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":92
 * 
 *             # Push the current block as indices
 *             if indices != NULL:             # <<<<<<<<<<<<<<
 *                 indices[i] = block
 * 
 */
    __pyx_t_1 = (__pyx_v_indices != NULL);
    if (__pyx_t_1) {

      /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":93
 *             # Push the current block as indices
 *             if indices != NULL:
 *                 indices[i] = block             # <<<<<<<<<<<<<<
 * 
 *     cdef void remove(self, unsigned short *indices, int count):
 */
      (__pyx_v_indices[__pyx_v_i]) = __pyx_v_block;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }

  __Pyx_RefNannyFinishContext();
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":95
 *                 indices[i] = block
 * 
 *     cdef void remove(self, unsigned short *indices, int count):             # <<<<<<<<<<<<<<
 *         '''Remove block from our list
 *         '''
 */

static  void __pyx_f_4kivy_8graphics_6buffer_6Buffer_remove(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self, unsigned short *__pyx_v_indices, int __pyx_v_count) {
  int __pyx_v_i;
  int __pyx_t_1;
  int __pyx_t_2;
  __Pyx_RefNannySetupContext("remove");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":100
 *         cdef int i
 * 
 *         for i in xrange(count):             # <<<<<<<<<<<<<<
 *             # Append the new indice as free block
 *             self.i_free -= 1
 */
  __pyx_t_1 = __pyx_v_count;
  for (__pyx_t_2 = 0; __pyx_t_2 < __pyx_t_1; __pyx_t_2+=1) {
    __pyx_v_i = __pyx_t_2;

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":102
 *         for i in xrange(count):
 *             # Append the new indice as free block
 *             self.i_free -= 1             # <<<<<<<<<<<<<<
 *             self.l_free[self.i_free] = indices[i]
 * 
 */
    __pyx_v_self->i_free = (__pyx_v_self->i_free - 1);

    /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":103
 *             # Append the new indice as free block
 *             self.i_free -= 1
 *             self.l_free[self.i_free] = indices[i]             # <<<<<<<<<<<<<<
 * 
 *     cdef void update(self, int index, void* blocks, int count):
 */
    (__pyx_v_self->l_free[__pyx_v_self->i_free]) = (__pyx_v_indices[__pyx_v_i]);
  }

  __Pyx_RefNannyFinishContext();
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":105
 *             self.l_free[self.i_free] = indices[i]
 * 
 *     cdef void update(self, int index, void* blocks, int count):             # <<<<<<<<<<<<<<
 *         '''Update count number of blocks starting at index with the data in blocks
 *         '''
 */

static  void __pyx_f_4kivy_8graphics_6buffer_6Buffer_update(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self, int __pyx_v_index, void *__pyx_v_blocks, int __pyx_v_count) {
  __Pyx_RefNannySetupContext("update");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":108
 *         '''Update count number of blocks starting at index with the data in blocks
 *         '''
 *         memcpy(self.data + (index * self.block_size), blocks, self.block_size * count)             # <<<<<<<<<<<<<<
 * 
 *     cdef int count(self):
 */
  memcpy((__pyx_v_self->data + (__pyx_v_index * __pyx_v_self->block_size)), __pyx_v_blocks, (__pyx_v_self->block_size * __pyx_v_count));

  __Pyx_RefNannyFinishContext();
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":110
 *         memcpy(self.data + (index * self.block_size), blocks, self.block_size * count)
 * 
 *     cdef int count(self):             # <<<<<<<<<<<<<<
 *         '''Return how many block are currently used
 *         '''
 */

static  int __pyx_f_4kivy_8graphics_6buffer_6Buffer_count(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self) {
  int __pyx_r;
  __Pyx_RefNannySetupContext("count");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":113
 *         '''Return how many block are currently used
 *         '''
 *         return self.i_free             # <<<<<<<<<<<<<<
 * 
 *     cdef int size(self):
 */
  __pyx_r = __pyx_v_self->i_free;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":115
 *         return self.i_free
 * 
 *     cdef int size(self):             # <<<<<<<<<<<<<<
 *         '''Return the size of the allocated buffer
 *         '''
 */

static  int __pyx_f_4kivy_8graphics_6buffer_6Buffer_size(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self) {
  int __pyx_r;
  __Pyx_RefNannySetupContext("size");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":118
 *         '''Return the size of the allocated buffer
 *         '''
 *         return self.block_size * self.block_count             # <<<<<<<<<<<<<<
 * 
 *     cdef void *pointer(self):
 */
  __pyx_r = (__pyx_v_self->block_size * __pyx_v_self->block_count);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":120
 *         return self.block_size * self.block_count
 * 
 *     cdef void *pointer(self):             # <<<<<<<<<<<<<<
 *         '''Return the data pointer
 *         '''
 */

static  void *__pyx_f_4kivy_8graphics_6buffer_6Buffer_pointer(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self) {
  void *__pyx_r;
  __Pyx_RefNannySetupContext("pointer");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":123
 *         '''Return the data pointer
 *         '''
 *         return self.data             # <<<<<<<<<<<<<<
 * 
 *     cdef void *offset_pointer(self, int offset):
 */
  __pyx_r = __pyx_v_self->data;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":125
 *         return self.data
 * 
 *     cdef void *offset_pointer(self, int offset):             # <<<<<<<<<<<<<<
 *         return self.data + (offset * self.block_size)
 * 
 */

static  void *__pyx_f_4kivy_8graphics_6buffer_6Buffer_offset_pointer(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *__pyx_v_self, int __pyx_v_offset) {
  void *__pyx_r;
  __Pyx_RefNannySetupContext("offset_pointer");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":126
 * 
 *     cdef void *offset_pointer(self, int offset):
 *         return self.data + (offset * self.block_size)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_r = (__pyx_v_self->data + (__pyx_v_offset * __pyx_v_self->block_size));
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
static struct __pyx_vtabstruct_4kivy_8graphics_6buffer_Buffer __pyx_vtable_4kivy_8graphics_6buffer_Buffer;

static PyObject *__pyx_tp_new_4kivy_8graphics_6buffer_Buffer(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *)o);
  p->__pyx_vtab = __pyx_vtabptr_4kivy_8graphics_6buffer_Buffer;
  if (__pyx_pf_4kivy_8graphics_6buffer_6Buffer_0__cinit__(o, __pyx_empty_tuple, NULL) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_4kivy_8graphics_6buffer_Buffer(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++Py_REFCNT(o);
    __pyx_pf_4kivy_8graphics_6buffer_6Buffer_1__dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --Py_REFCNT(o);
    PyErr_Restore(etype, eval, etb);
  }
  (*Py_TYPE(o)->tp_free)(o);
}

static PyMethodDef __pyx_methods_4kivy_8graphics_6buffer_Buffer[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Buffer = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_divide*/
  #endif
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_coerce*/
  #endif
  0, /*nb_int*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_long*/
  #else
  0, /*reserved*/
  #endif
  0, /*nb_float*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_oct*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*nb_hex*/
  #endif
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_inplace_divide*/
  #endif
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if PY_VERSION_HEX >= 0x02050000
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Buffer = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Buffer = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Buffer = {
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getreadbuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getwritebuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getsegcount*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getcharbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_getbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_releasebuffer*/
  #endif
};

PyTypeObject __pyx_type_4kivy_8graphics_6buffer_Buffer = {
  PyVarObject_HEAD_INIT(0, 0)
  __Pyx_NAMESTR("kivy.graphics.buffer.Buffer"), /*tp_name*/
  sizeof(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_4kivy_8graphics_6buffer_Buffer, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  #if PY_MAJOR_VERSION < 3
  0, /*tp_compare*/
  #else
  0, /*reserved*/
  #endif
  0, /*tp_repr*/
  &__pyx_tp_as_number_Buffer, /*tp_as_number*/
  &__pyx_tp_as_sequence_Buffer, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Buffer, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Buffer, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_HAVE_NEWBUFFER|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  __Pyx_DOCSTR("Buffer class is designed to manage very fast a list of fixed size block.\n    You can easily add and remove data from the buffer.\n    "), /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_4kivy_8graphics_6buffer_Buffer, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_4kivy_8graphics_6buffer_6Buffer_2__init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_4kivy_8graphics_6buffer_Buffer, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
  0, /*tp_del*/
  #if PY_VERSION_HEX >= 0x02060000
  0, /*tp_version_tag*/
  #endif
};

static PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    __Pyx_NAMESTR("buffer"),
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_s_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 0, 1, 0},
  {&__pyx_kp_s_3, __pyx_k_3, sizeof(__pyx_k_3), 0, 0, 1, 0},
  {&__pyx_n_s__SystemError, __pyx_k__SystemError, sizeof(__pyx_k__SystemError), 0, 0, 1, 1},
  {&__pyx_n_s____main__, __pyx_k____main__, sizeof(__pyx_k____main__), 0, 0, 1, 1},
  {&__pyx_n_s____test__, __pyx_k____test__, sizeof(__pyx_k____test__), 0, 0, 1, 1},
  {&__pyx_n_s__block_count, __pyx_k__block_count, sizeof(__pyx_k__block_count), 0, 0, 1, 1},
  {&__pyx_n_s__block_size, __pyx_k__block_size, sizeof(__pyx_k__block_size), 0, 0, 1, 1},
  {&__pyx_n_s__data, __pyx_k__data, sizeof(__pyx_k__data), 0, 0, 1, 1},
  {&__pyx_n_s__grow, __pyx_k__grow, sizeof(__pyx_k__grow), 0, 0, 1, 1},
  {&__pyx_n_s__i_free, __pyx_k__i_free, sizeof(__pyx_k__i_free), 0, 0, 1, 1},
  {&__pyx_n_s__l_free, __pyx_k__l_free, sizeof(__pyx_k__l_free), 0, 0, 1, 1},
  {&__pyx_n_s__range, __pyx_k__range, sizeof(__pyx_k__range), 0, 0, 1, 1},
  {&__pyx_n_s__xrange, __pyx_k__xrange, sizeof(__pyx_k__xrange), 0, 0, 1, 1},
  {0, 0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  __pyx_builtin_SystemError = __Pyx_GetName(__pyx_b, __pyx_n_s__SystemError); if (!__pyx_builtin_SystemError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #if PY_MAJOR_VERSION >= 3
  __pyx_builtin_xrange = __Pyx_GetName(__pyx_b, __pyx_n_s__range); if (!__pyx_builtin_xrange) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #else
  __pyx_builtin_xrange = __Pyx_GetName(__pyx_b, __pyx_n_s__xrange); if (!__pyx_builtin_xrange) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #endif
  return 0;
  __pyx_L1_error:;
  return -1;
}

static int __Pyx_InitCachedConstants(void) {
  __Pyx_RefNannySetupContext("__Pyx_InitCachedConstants");

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":45
 *         newptr = realloc(self.data, self.block_size * block_count)
 *         if newptr == NULL:
 *             raise SystemError('Unable to realloc memory for buffer')             # <<<<<<<<<<<<<<
 * 
 *         # Realloc work, put the new pointer
 */
  __pyx_k_tuple_2 = PyTuple_New(1); if (unlikely(!__pyx_k_tuple_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_k_tuple_2));
  __Pyx_INCREF(((PyObject *)__pyx_kp_s_1));
  PyTuple_SET_ITEM(__pyx_k_tuple_2, 0, ((PyObject *)__pyx_kp_s_1));
  __Pyx_GIVEREF(((PyObject *)__pyx_kp_s_1));
  __Pyx_GIVEREF(((PyObject *)__pyx_k_tuple_2));

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":53
 *         newptr = realloc(self.l_free, sizeof(int) * block_count)
 *         if newptr == NULL:
 *             raise SystemError('Unable to realloc memory for free list')             # <<<<<<<<<<<<<<
 *         self.l_free = <int *>newptr
 * 
 */
  __pyx_k_tuple_4 = PyTuple_New(1); if (unlikely(!__pyx_k_tuple_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_k_tuple_4));
  __Pyx_INCREF(((PyObject *)__pyx_kp_s_3));
  PyTuple_SET_ITEM(__pyx_k_tuple_4, 0, ((PyObject *)__pyx_kp_s_3));
  __Pyx_GIVEREF(((PyObject *)__pyx_kp_s_3));
  __Pyx_GIVEREF(((PyObject *)__pyx_k_tuple_4));
  __Pyx_RefNannyFinishContext();
  return 0;
  __pyx_L1_error:;
  __Pyx_RefNannyFinishContext();
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbuffer(void); /*proto*/
PyMODINIT_FUNC initbuffer(void)
#else
PyMODINIT_FUNC PyInit_buffer(void); /*proto*/
PyMODINIT_FUNC PyInit_buffer(void)
#endif
{
  PyObject *__pyx_t_1 = NULL;
  #if CYTHON_REFNANNY
  void* __pyx_refnanny = NULL;
  __Pyx_RefNanny = __Pyx_RefNannyImportAPI("refnanny");
  if (!__Pyx_RefNanny) {
      PyErr_Clear();
      __Pyx_RefNanny = __Pyx_RefNannyImportAPI("Cython.Runtime.refnanny");
      if (!__Pyx_RefNanny)
          Py_FatalError("failed to import 'refnanny' module");
  }
  __pyx_refnanny = __Pyx_RefNanny->SetupContext("PyMODINIT_FUNC PyInit_buffer(void)", __LINE__, __FILE__);
  #endif
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_empty_bytes = PyBytes_FromStringAndSize("", 0); if (unlikely(!__pyx_empty_bytes)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #ifdef __pyx_binding_PyCFunctionType_USED
  if (__pyx_binding_PyCFunctionType_init() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #endif
  /*--- Library function declarations ---*/
  /*--- Threads initialization code ---*/
  #if defined(__PYX_FORCE_INIT_THREADS) && __PYX_FORCE_INIT_THREADS
  #ifdef WITH_THREAD /* Python build with threading support? */
  PyEval_InitThreads();
  #endif
  #endif
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4(__Pyx_NAMESTR("buffer"), __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_NAMESTR(__Pyx_BUILTIN_MODULE_NAME));
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_module_is_main_kivy__graphics__buffer) {
    if (__Pyx_SetAttrString(__pyx_m, "__name__", __pyx_n_s____main__) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  }
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Constants init code ---*/
  if (unlikely(__Pyx_InitCachedConstants() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_vtabptr_4kivy_8graphics_6buffer_Buffer = &__pyx_vtable_4kivy_8graphics_6buffer_Buffer;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.clear = (void (*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *))__pyx_f_4kivy_8graphics_6buffer_6Buffer_clear;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.grow = (void (*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, int))__pyx_f_4kivy_8graphics_6buffer_6Buffer_grow;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.add = (void (*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, void *, unsigned short *, int))__pyx_f_4kivy_8graphics_6buffer_6Buffer_add;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.remove = (void (*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, unsigned short *, int))__pyx_f_4kivy_8graphics_6buffer_6Buffer_remove;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.count = (int (*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *))__pyx_f_4kivy_8graphics_6buffer_6Buffer_count;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.size = (int (*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *))__pyx_f_4kivy_8graphics_6buffer_6Buffer_size;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.pointer = (void *(*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *))__pyx_f_4kivy_8graphics_6buffer_6Buffer_pointer;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.offset_pointer = (void *(*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, int))__pyx_f_4kivy_8graphics_6buffer_6Buffer_offset_pointer;
  __pyx_vtable_4kivy_8graphics_6buffer_Buffer.update = (void (*)(struct __pyx_obj_4kivy_8graphics_6buffer_Buffer *, int, void *, int))__pyx_f_4kivy_8graphics_6buffer_6Buffer_update;
  if (PyType_Ready(&__pyx_type_4kivy_8graphics_6buffer_Buffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_SetVtable(__pyx_type_4kivy_8graphics_6buffer_Buffer.tp_dict, __pyx_vtabptr_4kivy_8graphics_6buffer_Buffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_SetAttrString(__pyx_m, "Buffer", (PyObject *)&__pyx_type_4kivy_8graphics_6buffer_Buffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4kivy_8graphics_6buffer_Buffer = &__pyx_type_4kivy_8graphics_6buffer_Buffer;
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\common.pxi":5
 * #
 * 
 * cdef double pi = 3.1415926535897931             # <<<<<<<<<<<<<<
 * cdef extern from "math.h":
 *     double cos(double) nogil
 */
  __pyx_v_4kivy_8graphics_6buffer_pi = 3.1415926535897931;

  /* "c:\Users\tito\Downloads\kivy\Kivy-1.0.9-w32\Kivy-1.0.9\kivy\graphics\buffer.pyx":1
 * include "common.pxi"             # <<<<<<<<<<<<<<
 * 
 * cdef class Buffer:
 */
  __pyx_t_1 = PyDict_New(); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_1));
  if (PyObject_SetAttr(__pyx_m, __pyx_n_s____test__, ((PyObject *)__pyx_t_1)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(((PyObject *)__pyx_t_1)); __pyx_t_1 = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  if (__pyx_m) {
    __Pyx_AddTraceback("init kivy.graphics.buffer");
    Py_DECREF(__pyx_m); __pyx_m = 0;
  } else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_ImportError, "init kivy.graphics.buffer");
  }
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
}

/* Runtime support code */

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static CYTHON_INLINE int __Pyx_CheckKeywordStrings(
    PyObject *kwdict,
    const char* function_name,
    int kw_allowed)
{
    PyObject* key = 0;
    Py_ssize_t pos = 0;
    while (PyDict_Next(kwdict, &pos, &key, 0)) {
        #if PY_MAJOR_VERSION < 3
        if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key)))
        #else
        if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key)))
        #endif
            goto invalid_keyword_type;
    }
    if ((!kw_allowed) && unlikely(key))
        goto invalid_keyword;
    return 1;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    return 0;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
    return 0;
}

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        name = first_kw_arg;
        while (*name && (**name != key)) name++;
        if (*name) {
            values[name-argnames] = value;
        } else {
            #if PY_MAJOR_VERSION < 3
            if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
            #else
            if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
            #endif
                goto invalid_keyword_type;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        _PyString_Eq(**name, key)) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            _PyString_Eq(**name, key)) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}

static CYTHON_INLINE long __Pyx_mod_long(long a, long b) {
    long r = a % b;
    r += ((r != 0) & ((r ^ b) < 0)) * b;
    return r;
}

static CYTHON_INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb) {
    PyObject *tmp_type, *tmp_value, *tmp_tb;
    PyThreadState *tstate = PyThreadState_GET();

    tmp_type = tstate->curexc_type;
    tmp_value = tstate->curexc_value;
    tmp_tb = tstate->curexc_traceback;
    tstate->curexc_type = type;
    tstate->curexc_value = value;
    tstate->curexc_traceback = tb;
    Py_XDECREF(tmp_type);
    Py_XDECREF(tmp_value);
    Py_XDECREF(tmp_tb);
}

static CYTHON_INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_GET();
    *type = tstate->curexc_type;
    *value = tstate->curexc_value;
    *tb = tstate->curexc_traceback;

    tstate->curexc_type = 0;
    tstate->curexc_value = 0;
    tstate->curexc_traceback = 0;
}


#if PY_MAJOR_VERSION < 3
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) Py_TYPE(type);
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }

    __Pyx_ErrRestore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

#else /* Python 3+ */

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    if (tb == Py_None) {
        tb = 0;
    } else if (tb && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto bad;
    }
    if (value == Py_None)
        value = 0;

    if (PyExceptionInstance_Check(type)) {
        if (value) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto bad;
        }
        value = type;
        type = (PyObject*) Py_TYPE(value);
    } else if (!PyExceptionClass_Check(type)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: exception class must be a subclass of BaseException");
        goto bad;
    }

    PyErr_SetObject(type, value);

    if (tb) {
        PyThreadState *tstate = PyThreadState_GET();
        PyObject* tmp_tb = tstate->curexc_traceback;
        if (tb != tmp_tb) {
            Py_INCREF(tb);
            tstate->curexc_traceback = tb;
            Py_XDECREF(tmp_tb);
        }
    }

bad:
    return;
}
#endif

static CYTHON_INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject* x) {
    const unsigned char neg_one = (unsigned char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned char" :
                    "value too large to convert to unsigned char");
            }
            return (unsigned char)-1;
        }
        return (unsigned char)val;
    }
    return (unsigned char)__Pyx_PyInt_AsUnsignedLong(x);
}

static CYTHON_INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject* x) {
    const unsigned short neg_one = (unsigned short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned short" :
                    "value too large to convert to unsigned short");
            }
            return (unsigned short)-1;
        }
        return (unsigned short)val;
    }
    return (unsigned short)__Pyx_PyInt_AsUnsignedLong(x);
}

static CYTHON_INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject* x) {
    const unsigned int neg_one = (unsigned int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned int" :
                    "value too large to convert to unsigned int");
            }
            return (unsigned int)-1;
        }
        return (unsigned int)val;
    }
    return (unsigned int)__Pyx_PyInt_AsUnsignedLong(x);
}

static CYTHON_INLINE char __Pyx_PyInt_AsChar(PyObject* x) {
    const char neg_one = (char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to char" :
                    "value too large to convert to char");
            }
            return (char)-1;
        }
        return (char)val;
    }
    return (char)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE short __Pyx_PyInt_AsShort(PyObject* x) {
    const short neg_one = (short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to short" :
                    "value too large to convert to short");
            }
            return (short)-1;
        }
        return (short)val;
    }
    return (short)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE int __Pyx_PyInt_AsInt(PyObject* x) {
    const int neg_one = (int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to int" :
                    "value too large to convert to int");
            }
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject* x) {
    const signed char neg_one = (signed char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed char" :
                    "value too large to convert to signed char");
            }
            return (signed char)-1;
        }
        return (signed char)val;
    }
    return (signed char)__Pyx_PyInt_AsSignedLong(x);
}

static CYTHON_INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject* x) {
    const signed short neg_one = (signed short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed short" :
                    "value too large to convert to signed short");
            }
            return (signed short)-1;
        }
        return (signed short)val;
    }
    return (signed short)__Pyx_PyInt_AsSignedLong(x);
}

static CYTHON_INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject* x) {
    const signed int neg_one = (signed int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed int" :
                    "value too large to convert to signed int");
            }
            return (signed int)-1;
        }
        return (signed int)val;
    }
    return (signed int)__Pyx_PyInt_AsSignedLong(x);
}

static CYTHON_INLINE int __Pyx_PyInt_AsLongDouble(PyObject* x) {
    const int neg_one = (int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to int" :
                    "value too large to convert to int");
            }
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject* x) {
    const unsigned long neg_one = (unsigned long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return (unsigned long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned long");
                return (unsigned long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        unsigned long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned long)-1;
        val = __Pyx_PyInt_AsUnsignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    const unsigned PY_LONG_LONG neg_one = (unsigned PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return (unsigned PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned PY_LONG_LONG");
                return (unsigned PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        unsigned PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE long __Pyx_PyInt_AsLong(PyObject* x) {
    const long neg_one = (long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to long");
            return (long)-1;
        }
        return (long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to long");
                return (long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (long)-1;
        val = __Pyx_PyInt_AsLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject* x) {
    const PY_LONG_LONG neg_one = (PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to PY_LONG_LONG");
            return (PY_LONG_LONG)-1;
        }
        return (PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to PY_LONG_LONG");
                return (PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject* x) {
    const signed long neg_one = (signed long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed long");
            return (signed long)-1;
        }
        return (signed long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed long");
                return (signed long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        signed long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed long)-1;
        val = __Pyx_PyInt_AsSignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject* x) {
    const signed PY_LONG_LONG neg_one = (signed PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed PY_LONG_LONG");
            return (signed PY_LONG_LONG)-1;
        }
        return (signed PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed PY_LONG_LONG");
                return (signed PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        signed PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsSignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static void __Pyx_WriteUnraisable(const char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    __Pyx_ErrFetch(&old_exc, &old_val, &old_tb);
    #if PY_MAJOR_VERSION < 3
    ctx = PyString_FromString(name);
    #else
    ctx = PyUnicode_FromString(name);
    #endif
    __Pyx_ErrRestore(old_exc, old_val, old_tb);
    if (!ctx) {
        PyErr_WriteUnraisable(Py_None);
    } else {
        PyErr_WriteUnraisable(ctx);
        Py_DECREF(ctx);
    }
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
#if PY_VERSION_HEX >= 0x02070000 && !(PY_MAJOR_VERSION==3&&PY_MINOR_VERSION==0)
    PyObject *ob = PyCapsule_New(vtable, 0, 0);
#else
    PyObject *ob = PyCObject_FromVoidPtr(vtable, 0);
#endif
    if (!ob)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", ob) < 0)
        goto bad;
    Py_DECREF(ob);
    return 0;
bad:
    Py_XDECREF(ob);
    return -1;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        __pyx_empty_bytes, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        __pyx_empty_bytes  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_unicode | t->is_str) {
            if (t->intern) {
                *t->p = PyUnicode_InternFromString(t->s);
            } else if (t->encoding) {
                *t->p = PyUnicode_Decode(t->s, t->n - 1, t->encoding, NULL);
            } else {
                *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
            }
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static CYTHON_INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   int is_true = x == Py_True;
   if (is_true | (x == Py_False) | (x == Py_None)) return is_true;
   else return PyObject_IsTrue(x);
}

static CYTHON_INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x) {
  PyNumberMethods *m;
  const char *name = NULL;
  PyObject *res = NULL;
#if PY_VERSION_HEX < 0x03000000
  if (PyInt_Check(x) || PyLong_Check(x))
#else
  if (PyLong_Check(x))
#endif
    return Py_INCREF(x), x;
  m = Py_TYPE(x)->tp_as_number;
#if PY_VERSION_HEX < 0x03000000
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Int(x);
  }
  else if (m && m->nb_long) {
    name = "long";
    res = PyNumber_Long(x);
  }
#else
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Long(x);
  }
#endif
  if (res) {
#if PY_VERSION_HEX < 0x03000000
    if (!PyInt_Check(res) && !PyLong_Check(res)) {
#else
    if (!PyLong_Check(res)) {
#endif
      PyErr_Format(PyExc_TypeError,
                   "__%s__ returned non-%s (type %.200s)",
                   name, name, Py_TYPE(res)->tp_name);
      Py_DECREF(res);
      return NULL;
    }
  }
  else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_TypeError,
                    "an integer is required");
  }
  return res;
}

static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static CYTHON_INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
#if PY_VERSION_HEX < 0x02050000
   if (ival <= LONG_MAX)
       return PyInt_FromLong((long)ival);
   else {
       unsigned char *bytes = (unsigned char *) &ival;
       int one = 1; int little = (int)*(unsigned char*)&one;
       return _PyLong_FromByteArray(bytes, sizeof(size_t), little, 0);
   }
#else
   return PyInt_FromSize_t(ival);
#endif
}

static CYTHON_INLINE size_t __Pyx_PyInt_AsSize_t(PyObject* x) {
   unsigned PY_LONG_LONG val = __Pyx_PyInt_AsUnsignedLongLong(x);
   if (unlikely(val == (unsigned PY_LONG_LONG)-1 && PyErr_Occurred())) {
       return (size_t)-1;
   } else if (unlikely(val != (unsigned PY_LONG_LONG)(size_t)val)) {
       PyErr_SetString(PyExc_OverflowError,
                       "value too large to convert to size_t");
       return (size_t)-1;
   }
   return (size_t)val;
}


#endif /* Py_PYTHON_H */
